//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniBook.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BOOKSTOREEntities : DbContext
    {
        public BOOKSTOREEntities()
            : base("name=BOOKSTOREEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIETDONHANG> CHITIETDONHANGs { get; set; }
        public virtual DbSet<DANHGIA> DANHGIAs { get; set; }
        public virtual DbSet<DONHANG> DONHANGs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<NXB> NXBs { get; set; }
        public virtual DbSet<SACH> SACHes { get; set; }
        public virtual DbSet<TACGIA> TACGIAs { get; set; }
        public virtual DbSet<THELOAI> THELOAIs { get; set; }
        public virtual DbSet<VAITRO> VAITROes { get; set; }
        public virtual DbSet<VOUCHER> VOUCHERs { get; set; }
        public virtual DbSet<QUANLI> QUANLIs { get; set; }
    
        public virtual ObjectResult<Nullable<int>> SoDonChuaHoanThanh(ObjectParameter sl)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SoDonChuaHoanThanh", sl);
        }
    
        public virtual ObjectResult<Nullable<int>> SoDonHangDaDat(ObjectParameter sl)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SoDonHangDaDat", sl);
        }
    
        public virtual ObjectResult<Nullable<int>> SoDonHoanThanh(ObjectParameter sl)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SoDonHoanThanh", sl);
        }
    
        public virtual ObjectResult<Nullable<int>> SoSanPhamBanDuoc(ObjectParameter sl)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SoSanPhamBanDuoc", sl);
        }
    
        public virtual ObjectResult<Nullable<double>> SoTienBanDuoc(ObjectParameter sotien)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("SoTienBanDuoc", sotien);
        }
    
        public virtual ObjectResult<Nullable<int>> SoSanPhamBanDuoc1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SoSanPhamBanDuoc1");
        }
    
        public virtual ObjectResult<Nullable<double>> SoTienBanDuoc1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("SoTienBanDuoc1");
        }
    }
}
